image: docker-registry.dp.nlmk.com/nlmk-redoc-swagger:latest

before_script:
  - swagger version
  - redoc-cli --version

validate:
  stage: test
  script:
    - make validate

pages:
  stage: deploy
  script:
  - redoc-cli bundle -o public/index.html index.yml
  artifacts:
    paths:
    - public
  only:
  - master
