swagger: "2.0"
host: "localhost"
basePath: "/v1"
schemes:
  - "http"
  - "https"
info:
  description: "Сервис мета информации"
  version: "1.0.0"
  title: "Metadata Service"
tags:
  - name: "swagger"
  - name: "iba"
paths:
  /swagger.json:
    $ref: paths/swagger.json.yml

  ########################################################
  # iba
  /ibas/servers/${iba_server_id}:
    $ref: paths/ibas/iba.yml

  /ibas/servers/${iba_server_id}/signals:
    $ref: paths/ibas/server_signals.yml

  /ibas/servers/${iba_server_id}/signals/mapping:
    $ref: paths/ibas/server_signals_mapping.yml

  /ibas/gates:
    $ref: paths/ibas/gates.yml
  
  /ibas/gates/${gate_name}:
    $ref: paths/ibas/gates_gate.yml
  
  /ibas/gates/${gate_name}/mnts:
    $ref: paths/ibas/gates_gate_mnts.yml

  /ibas/gates/${gate_name}/mnts/${mnt}:
    $ref: paths/ibas/gates_gate_mnts_mnt.yml

  /ibas/gates/${gate_name}/mnts/${mnt}/signals/mapping:
    $ref: paths/ibas/gate_mnt_signals_mapping.yml

  # topics
#  /ibas/topics/${topic}/mapping:
#    $ref: paths/ibas/server_signals_mapping.yml